name: ecommerce_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # Disarankan untuk mengunci versi mayor

dependencies:
  flutter:
    sdk: flutter

  # UI & UX Packages
  cached_network_image: ^3.4.1 # Cache gambar dari network
  carousel_slider: ^4.2.1      # Carousel untuk banner
  cupertino_icons: ^1.0.8      # Ikon gaya iOS
  lottie: ^3.1.2               # Animasi Lottie (JSON)

  # State Management
  flutter_riverpod: ^2.5.1 # State management utama

  # Networking & Data
  dio: ^5.4.3              # HTTP client untuk interaksi API
  json_annotation: ^4.9.0  # Anotasi untuk json_serializable

  # Data Persistence & Models
  freezed_annotation: ^2.4.1 # Anotasi untuk code generation model
  shared_preferences: ^2.2.3   # Simpan data simpel (key-value)

  # Utilities
  intl: ^0.19.0 # Untuk formatting tanggal, angka, dll.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.11      # Runner untuk code generation
  freezed: ^2.5.2            # Generator untuk data class immutable
  json_serializable: ^6.8.0  # Generator untuk fromJson/toJson

  # App Icon Generation
  flutter_launcher_icons: ^0.13.1 # Membuat ikon aplikasi otomatis

  # Code Quality
  flutter_lints: ^4.0.0 # Aturan linting untuk kode yang baik

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/icon/ # Tambahkan ini agar konsisten

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_antimarket.png"
  min_sdk_android: 21